name: Submit Private Repo
description: Provide your private repo link for instructor validation (no spoilers).
title: "Private repo submission: "
labels:
  - submission
body:
  - type: input
    id: student_name
    attributes:
      label: Student name
      placeholder: First Last
    validations:
      required: true
  - type: input
    id: private_repo_url
    attributes:
      label: Private repo URL
      placeholder: https://github.com/yourname/your-private-repo
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email (optional)
      placeholder: you@example.edu
    validations:
      required: false
  - type: checkboxes
    id: no_spoilers
    attributes:
      label: No spoilers confirmation
      options:
        - label: I confirm my private repo does not contain public solutions or exploit payloads.
          required: true
  - type: checkboxes
    id: completion
    attributes:
      label: Completion checklist
      options:
        - label: I added the instructor as a collaborator.
          required: true
        - label: I used the submission template in my private repo.
          required: true
        - label: My public summary contains no spoilers.
          required: true

